### ISSUE TITLE
Confused on Division Implementation

### ISSUE THREAD

**Issue by rmehta33** [mgriebling/BigDecimal#7]
Hello!

More of an implementation question than anything else, buy why does the '/' operation truncate by default? 

And if possible, can there instead be two '/' functions? One that keeps the original functionality but returns it as the relevant int type instead, and another that just returns the '.divide' function as a decimal. Or perhaps replace the current function with '÷' and use '/' for '.divide'?

This would just make it much easier to use the package as a drop in replacement for a double. If you agree with the change, I can even create the pull request.

**Comment by mgriebling** [comment]
Sure go ahead.

**Comment by mgriebling** [comment]
Done, I believe.

**Comment by mgriebling** [comment]
To answer your question about the truncation in the '/' division, have a look at the README.md file. It explains the design decisions made. Basically some divisions could result in infinite decimal calculations so this is a practical way of avoiding this situation. A 'divide' function provides additional arguments to allow as much precision as desired during extended calculations.

**Comment by rmehta33** [comment]
Hey! Thank you for the follow ups. Yup makes sense. I ended up needing a lot more 
relatively niche modifications for my particular use case, so it was just easier to create a fork. But honestly thanks for making and supporting the library, it’s been a big help!
